apiVersion: skaffold/v2beta12
kind: Config
build:
  googleCloudBuild: {}
  artifacts:
    - image: gcr.io/personal-project-289714/endgame
      context: ./
deploy:
  kubectl:
    manifests:
      - kubernetes/local/endgame-deployment.yaml
portForward:
  - resourceType: deployment
    resourceName: endgame-website
    port: 8000
    localPort: 8000
