apiVersion: v1
kind: Service
metadata:
  name: boilerplatesvc
  namespace: resume
  labels:
    app: boilerplate-website
spec:
  selector:
    app: boilerplate-website
    tier: deploy
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
